# Generated by Django 3.2.3 on 2023-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True)),
                ('day', models.IntegerField(blank=True)),
                ('hour', models.IntegerField(blank=True)),
                ('minute', models.IntegerField(blank=True)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('neighbor', models.CharField(blank=True, max_length=100)),
                ('x', models.CharField(blank=True, max_length=20)),
                ('y', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
